import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../../../');
const SANITY_DIR = path.join(ROOT, 'Sanity');
const REPORT_JSON = path.join(SANITY_DIR, 'playwright-report.json');

function getVersion() {
  const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
  return pkg.version ?? 'unknown';
}

function getBranch() {
  try {
    return fs.readFileSync(path.join(ROOT, '.git/HEAD'), 'utf8').replace('ref: refs/heads/', '').trim();
  } catch {
    return 'unknown';
  }
}

function getDate() {
  return new Date().toISOString().split('T')[0];
}

function statusIcon(passed) {
  return passed ? '✅' : '❌';
}

function parsePlaywrightReport() {
  if (!fs.existsSync(REPORT_JSON)) {
    return null;
  }
  return JSON.parse(fs.readFileSync(REPORT_JSON, 'utf8'));
}

function buildPlaywrightSection(report) {
  if (!report) {
    return '## Playwright Sanity\n\n> No Playwright report found. Run `npm run sanity` first.\n';
  }

  const suites = report.suites ?? [];
  const allTests = [];

  function collectTests(suite) {
    for (const spec of suite.specs ?? []) {
      for (const test of spec.tests ?? []) {
        allTests.push({
          title: spec.title,
          status: test.status,
        });
      }
    }
    for (const child of suite.suites ?? []) {
      collectTests(child);
    }
  }

  for (const suite of suites) {
    collectTests(suite);
  }

  const sanity = allTests.filter((t) => t.title.startsWith('[sanity]'));
  const darkMode = allTests.filter((t) => t.title.startsWith('[dark-mode]'));
  const interactions = allTests.filter((t) => t.title.startsWith('[interactions]'));

  const summary = (tests) => {
    const passed = tests.filter((t) => t.status === 'expected').length;
    const failed = tests.filter((t) => t.status === 'unexpected').length;
    const skipped = tests.filter((t) => t.status === 'skipped').length;
    return { passed, failed, skipped, total: tests.length };
  };

  const sanitySum = summary(sanity);
  const darkSum = summary(darkMode);
  const interactionsSum = summary(interactions);
  const failedTests = allTests.filter((t) => t.status === 'unexpected');

  let section = `## Playwright Sanity Results\n\n`;
  section += `| Suite | Passed | Failed | Skipped | Total |\n`;
  section += `|-------|--------|--------|---------|-------|\n`;
  section += `| Page Render (sanity) | ${sanitySum.passed} | ${sanitySum.failed} | ${sanitySum.skipped} | ${sanitySum.total} |\n`;
  section += `| Dark Mode | ${darkSum.passed} | ${darkSum.failed} | ${darkSum.skipped} | ${darkSum.total} |\n`;
  section += `| Interactions | ${interactionsSum.passed} | ${interactionsSum.failed} | ${interactionsSum.skipped} | ${interactionsSum.total} |\n`;

  if (failedTests.length > 0) {
    section += `\n### Failed Tests\n\n`;
    for (const t of failedTests) {
      section += `- ❌ \`${t.title}\`\n`;
    }
  }

  return section;
}

function buildCheckSection(label, output) {
  const passed = output?.exitCode === 0;
  const errors = output?.output ?? '';
  return `## ${label}\n\n${statusIcon(passed)} ${passed ? 'Passed' : `Failed:\n\`\`\`\n${errors.slice(0, 2000)}\n\`\`\``}\n`;
}

function main() {
  const args = process.argv.slice(2);
  const data = {};

  for (let i = 0; i < args.length; i += 2) {
    if (args[i] && args[i + 1]) {
      try {
        data[args[i].replace('--', '')] = JSON.parse(args[i + 1]);
      } catch {
        data[args[i].replace('--', '')] = { raw: args[i + 1] };
      }
    }
  }

  const version = getVersion();
  const branch = getBranch();
  const date = getDate();
  const playwrightReport = parsePlaywrightReport();

  const overallPassed =
    (data.typecheck?.exitCode === 0) &&
    (data.build?.exitCode === 0) &&
    (data.portaltypecheck?.exitCode === 0) &&
    (!playwrightReport || (playwrightReport.stats?.unexpected ?? 0) === 0);

  const report = `# Grid Table Portal Sanity Report — release/${version}

**Date:** ${date}
**Branch:** ${branch}
**Version:** ${version}
**Overall Status:** ${statusIcon(overallPassed)} ${overallPassed ? 'PASSED' : 'FAILED'}

---

${buildCheckSection('Library TypeScript', data.typecheck)}

---

${buildCheckSection('Library Build', data.build)}

---

${buildCheckSection('Portal TypeScript', data.portaltypecheck)}

---

${buildPlaywrightSection(playwrightReport)}

---

*Generated by \`portal/e2e/scripts/generate-report.mjs\`*
`;

  if (!fs.existsSync(SANITY_DIR)) {
    fs.mkdirSync(SANITY_DIR, { recursive: true });
  }

  const filename = path.join(SANITY_DIR, `sanity-release-${version}.md`);
  fs.writeFileSync(filename, report, 'utf8');
  console.log(`✅ Sanity report written to: ${filename}`);
}

main();
