import { createBreakpoints } from '@forgedevstack/rail';

export const HOME_DEMOS_RAIL_CLASS = 'gt-home-demos-rail';
export const HOME_DEMOS_RAIL_HEIGHT_PX = 460;
export const HOME_DEMOS_RAIL_SPACE_MOBILE_PX = 12;
export const HOME_DEMOS_RAIL_SPACE_TABLET_PX = 16;
export const HOME_DEMOS_RAIL_SPACE_DESKTOP_PX = 20;
export const HOME_DEMOS_RAIL_BREAK_TABLET_PX = 768;
export const HOME_DEMOS_RAIL_BREAK_DESKTOP_PX = 1100;
export const HOME_DEMOS_RAIL_SLIDES_MOBILE = 1;
export const HOME_DEMOS_RAIL_SLIDES_TABLET = 2;
export const HOME_DEMOS_RAIL_SLIDES_DESKTOP = 3;
export const HOME_DEMOS_AUTOPLAY_MS = 4800;

export const HOME_DEMOS_BREAKPOINTS = createBreakpoints(
  {
    0: HOME_DEMOS_RAIL_SLIDES_MOBILE,
    [HOME_DEMOS_RAIL_BREAK_TABLET_PX]: HOME_DEMOS_RAIL_SLIDES_TABLET,
    [HOME_DEMOS_RAIL_BREAK_DESKTOP_PX]: HOME_DEMOS_RAIL_SLIDES_DESKTOP,
  },
  {
    spaceBetween: {
      0: HOME_DEMOS_RAIL_SPACE_MOBILE_PX,
      [HOME_DEMOS_RAIL_BREAK_TABLET_PX]: HOME_DEMOS_RAIL_SPACE_TABLET_PX,
      [HOME_DEMOS_RAIL_BREAK_DESKTOP_PX]: HOME_DEMOS_RAIL_SPACE_DESKTOP_PX,
    },
  },
);
