const PORTAL_ROUTES = [
  '/',
  '/demos',
  '/demos/features',
  '/demos/enterprise-grid',
  '/demos/release-1-1-4',
  '/demos/release-1-1-5',
  '/demos/touch-gestures',
  '/demos/infinite-scroll',
  '/demos/saved-views',
  '/demos/advanced-filter-builder',
  '/demos/pinned-row-groups',
  '/demos/column-formula-engine',
  '/demos/virtualization',
  '/demos/basic',
  '/demos/finance',
  '/demos/hr',
  '/demos/accessibility',
  '/demos/master-detail',
  '/demos/persisted-state',
  '/demos/server-driven',
  '/demos/column-grouping',
  '/demos/theme-playground',
  '/playground',
  '/theme-builder',
  '/changelog',
  '/skills',
  '/docs/getting-started',
  '/docs/api-reference',
  '/docs/enterprise-grid',
  '/docs/release-1-1-5',
];

const DARK_MODE_SAMPLE_ROUTES = [
  '/',
  '/demos/basic',
  '/demos/features',
  '/demos/enterprise-grid',
  '/playground',
  '/docs/getting-started',
  '/skills',
];

module.exports = { PORTAL_ROUTES, DARK_MODE_SAMPLE_ROUTES };
