import type { ReactNode, CSSProperties, MouseEvent } from 'react';
import type { RowData, ColumnDefinition, ColumnState, TouchGesturesConfig } from '@/types';
import type { CellClickEvent } from '../GridCell/GridCell.types';

export interface GridRowProps<T extends RowData = RowData> {
  row: T;
  rowIndex: number;
  columns: ColumnDefinition<T>[];
  columnStates: ColumnState[];
  isSelected?: boolean;
  isExpanded?: boolean;
  isDisabled?: boolean;
  applyHiddenOnMobile?: boolean;
  stackedMobileLayout?: boolean;
  showMobileLabels?: boolean;
  className?: string;
  style?: CSSProperties;
  onClick?: (row: T, index: number) => void;
  onDoubleClick?: (row: T, index: number) => void;
  onContextMenu?: (row: T, index: number, event: MouseEvent) => void;
  onLongPressContextMenu?: (row: T, index: number, clientX: number, clientY: number) => void;
  onCellClick?: (event: CellClickEvent<T>) => void;
  onSelect?: (selected: boolean) => void;
  onExpand?: (expanded: boolean) => void;
  enableSelection?: boolean;
  enableExpansion?: boolean;
  renderExpansion?: (row: T, rowId: string | number) => ReactNode;
  getRowId: (row: T) => string | number;
  draggable?: boolean;
  onDragStart?: () => void;
  onDragOver?: (e: React.DragEvent) => void;
  onDragEnd?: () => void;
  onDrop?: (e: React.DragEvent) => void;
  treeToggle?: () => void;
  treeHasChildren?: boolean;
  treeIsExpanded?: boolean;
  treeIndent?: number;
  dragHandleIcon?: ReactNode;
  treeToggleIcon?: ReactNode;
  expandRowIcon?: ReactNode;
  enableCellEdit?: boolean;
  onCellSave?: (rowId: string | number, columnId: string, oldValue: unknown, newValue: unknown) => void;
  onEditNavigate?: (rowIndex: number, colIndex: number, direction: 1 | -1) => void;
  selectOnEditFocus?: boolean;
  onGroupToggle?: (groupKey: string) => void;
  groupExpanded?: boolean;
  getCellClassName?: (rowIndex: number, columnId: string) => string;
  touchGestures?: TouchGesturesConfig<T>;
  onRangeMouseDown?: (rowIndex: number, colIndex: number, event: React.MouseEvent) => void;
  onRangeMouseEnter?: (rowIndex: number, colIndex: number) => void;
  onFillHandleMouseDown?: (rowIndex: number, colIndex: number, event: React.MouseEvent) => void;
  showFillHandleForCell?: (rowIndex: number, colIndex: number) => boolean;
}
